// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCucQgs44cE7Y4NByZy5uHgudAR33aYCQQ',
    appId: '1:416331207585:web:160b8f9f74c47e6bb171e0',
    messagingSenderId: '416331207585',
    projectId: 'backend-practise-b5f09',
    authDomain: 'backend-practise-b5f09.firebaseapp.com',
    databaseURL: 'https://backend-practise-b5f09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-practise-b5f09.appspot.com',
    measurementId: 'G-09SZ0MLYNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqVngyGvUC9GorXX13MONOlOiekOTh79I',
    appId: '1:416331207585:android:570e71db9e3c2ca8b171e0',
    messagingSenderId: '416331207585',
    projectId: 'backend-practise-b5f09',
    databaseURL: 'https://backend-practise-b5f09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-practise-b5f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqWmzF7Um_ZiasdrALmJs70NdxGt8kgHw',
    appId: '1:416331207585:ios:8ed9f3bc33ebd34eb171e0',
    messagingSenderId: '416331207585',
    projectId: 'backend-practise-b5f09',
    databaseURL: 'https://backend-practise-b5f09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-practise-b5f09.appspot.com',
    androidClientId: '416331207585-vk7osrrgsp9e7a93up0f9rf3ao5nqvr0.apps.googleusercontent.com',
    iosBundleId: 'com.tunkinnovation.chnatingv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqWmzF7Um_ZiasdrALmJs70NdxGt8kgHw',
    appId: '1:416331207585:ios:51f7972a82ca77a6b171e0',
    messagingSenderId: '416331207585',
    projectId: 'backend-practise-b5f09',
    databaseURL: 'https://backend-practise-b5f09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-practise-b5f09.appspot.com',
    androidClientId: '416331207585-vk7osrrgsp9e7a93up0f9rf3ao5nqvr0.apps.googleusercontent.com',
    iosBundleId: 'com.bitwise.chantingview.chantingview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCucQgs44cE7Y4NByZy5uHgudAR33aYCQQ',
    appId: '1:416331207585:web:a9c9fc37dd889063b171e0',
    messagingSenderId: '416331207585',
    projectId: 'backend-practise-b5f09',
    authDomain: 'backend-practise-b5f09.firebaseapp.com',
    databaseURL: 'https://backend-practise-b5f09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-practise-b5f09.appspot.com',
    measurementId: 'G-W0TRLKF10G',
  );

}